export {default as SvgX} from '@/public/media/icons/x-symbol-svgrepo-com.svg'
export {default as SvgActive} from '@/public/media/icons/check-mark-white-outline-svgrepo-com.svg'
export {default as SvgInactive} from '@/public/media/icons/check-mark-black-outline-svgrepo-com.svg'
export {default as SvgLoading} from '@/public/media/icons/bouncing-circles.svg'
export {default as SvgSun} from '@/public/media/icons/sun-svgrepo-com.svg'
export {default as SvgMoon} from '@/public/media/icons/moon-svgrepo-com.svg'
