import Head from "next/head";
import { ThemeProvider } from "styled-components";
import MainPage from "components";
import themes from "styles/themes";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThemeProvider theme={themes.defaultTheme}>
          <MainPage />
        </ThemeProvider>
      </main>
    </>
  );
}
